#!/usr/bin/env bash

CURRENT_FILE=$(readlink -f "$0")
DOTFILES=$(dirname "$CURRENT_FILE")

link() {
    # link dot -> file, if dot exists, backup it to bak
    file=$DOTFILES/files/$1
    dot=~/.$1
    bak=~/.$1.bak
    echo "[Linking] $1"
    if [ -h $dot ]; then
        if [ "$(readlink $dot)" != "$file" ]; then
            echo "Different symlink, backup"
            mv $dot $bak
        else
            echo "Already linked!"
            return 0
        fi
    elif [ -e $dot ]; then
        echo "Already exist, backup"
        mv $dot $bak
    fi
    ln -s $file $dot
}

link_all() {
    for each in $DOTFILES/files/*; do
        if [ -e $each ]; then
            link `basename $each`
        fi
    done
    echo "[All linked]"
}

git_clone() {
    if ! [[ -d ~/.antigen ]]; then
        git clone https://github.com/zsh-users/antigen.git ~/.antigen
    fi
    if ! [[ -d ~/.vim/bundle/vundle ]]; then
        git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
    fi
    vi +BundleInstall +qall
}

link_all
git_clone

