#!/usr/bin/env bash

CURRENT_FILE=$(readlink -f "$0")
DOTFILES=$(dirname "$CURRENT_FILE")

link() {
    # link dot -> file, if dot exists, backup it to bak
    file=$DOTFILES/files/$1
    dot=~/.$1
    bak=~/.$1.bak
    printf "[linking] %-30s -> %s\n" $dot $file
    if [ -h $dot ]; then
        if [ "$(readlink $dot)" != "$file" ]; then
            printf "Different symlink, backup\n"
            mv $dot $bak
        else
            printf "Already linked!\n"
            return 0
        fi
    elif [ -e $dot ]; then
        printf "Already exist, backup\n"
        mv $dot $bak
    fi
    ln -s $file $dot
}

link_all() {
    for each in $DOTFILES/files/*; do
        if [ -e $each ]; then
            link `basename $each` 
        fi
    done
    echo "dotfiles linked"
    return 0
}

git_clone() {
    if ! [[ -d ~/.oh-my-zsh ]]; then
	git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
    fi
    if ! [[ -d ~/.vim/bundle/vundle ]]; then
        git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
    fi
    vi +BundleInstall +qall
    return 0
}

link_all
git_clone

