#!/usr/bin/env bash

CURRENT_FILE=$(readlink -f "$0")
DOTFILES=$(dirname "$CURRENT_FILE")

if [ -z $XDG_CONFIG_HOME ]; then
    XDG_CONFIG_HOME=$HOME/.config
fi

link() {
    # link $src <- $dst_prefix$basename
    # if $src exists, backup it to $backup
    src=$1
    dst_prefix=$2
    basename=$(basename $src)
    target=${dst_prefix}${basename}
    backup=${target}.bak
    printf "[Linking] %-15s\t" $basename
    if [ -h $target ]; then
        if [ "$(readlink $target)" != "$src" ]; then
            printf "Different symlink, backup... "
            mv $target $backup
        else
            printf "Already linked!\n"
            return 0
        fi
    elif [ -e $target ]; then
        printf "Already exist, backup... "
        mv $target $backup
    fi
    ln -s $src $target
    printf "OK!\n"
}

link-all() {
    echo "[files]"
    for each in $DOTFILES/files/*; do
        link $each "$HOME/."
    done
    echo "[config]"
    mkdir -p $XDG_CONFIG_HOME
    for each in $DOTFILES/config/*; do
        link $each "$XDG_CONFIG_HOME/"
    done
    echo "[All linked]"
}

clone() {
    name=$1
    dir=$2
    repo=$3
    if ! [ -d $dir ]; then
        echo "[Cloning] $name"
        git clone $repo $dir
    fi
}

clone-repos() {
    clone zgen   ~/.zgen              https://github.com/zlsun/zgen.git
    clone vundle ~/.vim/bundle/vundle https://github.com/gmarik/vundle.git
}

install-vundles() {
    vim +VundleInstall +qall
}

link-all
clone-repos
install-vundles
echo "[Done]"

