#!/usr/bin/env bash

move-to-dotfiles () {
    for dotfile in "$@"; do
        target="$DOTFILES/files/${dotfile:1}"
        mv ${dotfile} ${target}
        ln -s ${target} ${dotfile}
    done
}

link-to-dotfiles () {
    for dotfile in "$@"; do
        target="$DOTFILES/files/${dotfile:1}"
        ln -s ${target} ${dotfile}
    done
}

