#!/usr/bin/env bash

CURRENT_FILE=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$CURRENT_FILE")
DOTFILES=$(dirname "$SCRIPT_DIR")

link() {
    # link dot -> file, if dot exists, backup it to bak
    file=$DOTFILES/$1
    dot=~/.$1
    bak=~/.$1.bak
    printf "[linking] %-30s -> %s\n" $dot $file
    if [ -h $dot ]; then
        if [ "$(readlink $dot)" != "$file" ]; then
            printf "Different symlink, backup\n"
            mv $dot $bak
        else
            printf "Already linked!\n"
            return 0
        fi
    elif [ -e $dot ]; then
        printf "Already exist, backup\n"
        mv $dot $bak
    fi
    ln -s $file $dot
}

# bash
link bashrc
link bash_aliases
link bash_completion
link bash_funcs
link bash_logout
link profile

# vim
link vim
link vimrc
link vimrc.bundles
# link vimrc.local
# link vimrc.before.local
# link vimrc.bundles.local
# link gvimrc.local
link NERDTreeBookmarks

# zsh
link zshrc
link zshenv
link warprc

# others
link gtkrc-2.0
link gitconfig
link pydistutils.cfg
link pip

