#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [[ -x "$f" ]] && . "$f"
    done
    unset f
fi

[[ -f $HOME/.Xmodmap ]] && xmodmap $HOME/.Xmodmap
[[ -f $HOME/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# Swap Caps-Lock and Escape
setxkbmap -option caps:swapescape

exec i3
