# User environment variables

export DEV_HOME=~/dev

# JDK
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=$CLASSPATH:.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=${JAVA_HOME}:${JAVA_HOME}/bin:${JAVA_HOME}/lib:${JRE_HOME}/bin:$PATH

# Android SDK
export ANDROID_SDK_ROOT=$DEV_HOME/android/sdk
export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools:$PATH

# Android NDK
export NDK_ROOT=$DEV_HOME/android/ndk
export PATH=$NDK_ROOT/platform-tools:$NDK_ROOT/tools:$PATH

# ANT
export ANT_ROOT=/usr/share/ant/bin
export PATH=$ANT_ROOT:$PATH

# cocos2d-x
export COCOS2DX=$DEV_HOME/cocos/cocos2d-x
export COCOS_CONSOLE_ROOT=$COCOS2DX/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH
export COCOS_TEMPLATES_ROOT=$COCOS2DX/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH

# Go
export GOROOT=/usr/lib/go
export GOARCH=amd64
export GOOS=linux
export GOPATH=$DEV_HOME/go
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

export PATH=~/.bin:$PATH
export PATH=~/.local/bin:$PATH

# cabal
export PATH=$HOME/.cabal/bin:$PATH

# ccache
# export PATH=/usr/lib/ccache/bin/:$PATH
export PATH=/usr/lib/colorgcc/bin/:$PATH
export CCACHE_PATH=/usr/bin
export CCACHE_DIR=/tmp/ccache

export MANPATH=/usr/local/man:$MANPATH

# Compilation flags
# export ARCHFLAGS="-arch x86_64"
export CPLUS_INCLUDE_PATH=~/proj/sunlib/include/

# applications
export VISUAL=vim
export EDITOR=vim
export PAGER=less
export XOPEN=mimeo
export BROWSER=google-chrome-unstable

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# Locale
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
export LC_TIME=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

# Enable Xft
export GDK_USE_XFT=1
export QT_XFT=true

