
autoload -U zmv

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

source ~/.zgen/zgen.zsh

if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    zgen loadall <<EOBUNDLES
        robbyrussell/oh-my-zsh plugins/atom
        robbyrussell/oh-my-zsh plugins/autopep8
        robbyrussell/oh-my-zsh plugins/cabal
        robbyrussell/oh-my-zsh plugins/colored-man
        robbyrussell/oh-my-zsh plugins/colorize
        robbyrussell/oh-my-zsh plugins/command-not-found
        robbyrussell/oh-my-zsh plugins/common-aliases
        robbyrussell/oh-my-zsh plugins/copydir
        robbyrussell/oh-my-zsh plugins/copyfile
        robbyrussell/oh-my-zsh plugins/cp
        robbyrussell/oh-my-zsh plugins/dircycle
        robbyrussell/oh-my-zsh plugins/django
        robbyrussell/oh-my-zsh plugins/extract
        robbyrussell/oh-my-zsh plugins/gem
        robbyrussell/oh-my-zsh plugins/git
        robbyrussell/oh-my-zsh plugins/github
        robbyrussell/oh-my-zsh plugins/gitignore
        robbyrussell/oh-my-zsh plugins/gradle
        robbyrussell/oh-my-zsh plugins/history
        robbyrussell/oh-my-zsh plugins/jsontools
        robbyrussell/oh-my-zsh plugins/node
        robbyrussell/oh-my-zsh plugins/npm
        robbyrussell/oh-my-zsh plugins/pep8
        robbyrussell/oh-my-zsh plugins/pip
        robbyrussell/oh-my-zsh plugins/python
        robbyrussell/oh-my-zsh plugins/ruby
        robbyrussell/oh-my-zsh plugins/sublime
        robbyrussell/oh-my-zsh plugins/sudo
        robbyrussell/oh-my-zsh plugins/themes
        robbyrussell/oh-my-zsh plugins/vundle
        robbyrussell/oh-my-zsh plugins/web-search
        robbyrussell/oh-my-zsh plugins/z

        zlsun/umake

        supercrabtree/k

        zsh-users/zsh-syntax-highlighting
        zsh-users/zsh-completions src
        zsh-users/zsh-history-substring-search

        # autosuggestions should be loaded last
        tarruda/zsh-autosuggestions

EOBUNDLES

    zgen load zlsun/avit-mod avit-mod

    zgen save
fi

# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# bind UP and DOWN arrow keys (compatibility fallback
# for Ubuntu 12.04, Fedora 21, and MacOSX 10.9 users)
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# bind P and N for EMACS mode
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Enable autosuggestions automatically.
zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init

# User configuration

find_duplicate() {
    local dir=${1:-.}
    find $dir -type f -print0 | xargs -0 -n1 md5sum | sort -k 1,32 | uniq -w 32 -d --all-repeated=separate | sed -e 's/^[0-9a-f]*\ *//;'
}

fawk() {
    local first="awk '{print "
    local last="}'"
    local cmd="${first}\$${1}${last}"
    eval $cmd
}

alias mmv='noglob zmv -W'

alias sga='sudo apt-get autoremove'
alias sgd='sudo apt-get dist-upgrade'
alias sgg='sudo apt-get upgrade'
alias sgi='sudo apt-get install'
alias sgp='sudo apt-get remove --purge'
alias sgr='sudo apt-get remove'
alias sgu='sudo apt-get update'
alias sgs='apt-cache search'
alias sgf='apt-file search'

alias v='vim'
alias svi='sudo vim'
alias vimrc='vim ~/.vimrc'

alias -g X='| xargs'

alias fuck='eval $(thefuck $(fc -ln -1))'
alias f='fuck'

alias k='k -h'
alias ka='k -h -A'

alias gg='git gui'

eval `dircolors ~/.dircolors`

