
ENABLE_CORRECTION="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"

source ~/.zgen/zgen.zsh

if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    zgen loadall <<EOBUNDLES
        robbyrussell/oh-my-zsh plugins/atom
        robbyrussell/oh-my-zsh plugins/autopep8
        robbyrussell/oh-my-zsh plugins/cabal
        robbyrussell/oh-my-zsh plugins/colorize
        robbyrussell/oh-my-zsh plugins/command-not-found
        robbyrussell/oh-my-zsh plugins/common-aliases
        robbyrussell/oh-my-zsh plugins/copydir
        robbyrussell/oh-my-zsh plugins/copyfile
        robbyrussell/oh-my-zsh plugins/cp
        robbyrussell/oh-my-zsh plugins/dircycle
        robbyrussell/oh-my-zsh plugins/django
        robbyrussell/oh-my-zsh plugins/extract
        robbyrussell/oh-my-zsh plugins/gem
        robbyrussell/oh-my-zsh plugins/git
        robbyrussell/oh-my-zsh plugins/github
        robbyrussell/oh-my-zsh plugins/gitignore
        robbyrussell/oh-my-zsh plugins/gradle
        robbyrussell/oh-my-zsh plugins/history
        robbyrussell/oh-my-zsh plugins/jsontools
        robbyrussell/oh-my-zsh plugins/node
        robbyrussell/oh-my-zsh plugins/npm
        robbyrussell/oh-my-zsh plugins/pep8
        robbyrussell/oh-my-zsh plugins/pip
        robbyrussell/oh-my-zsh plugins/python
        robbyrussell/oh-my-zsh plugins/ruby
        robbyrussell/oh-my-zsh plugins/sublime
        robbyrussell/oh-my-zsh plugins/sudo
        robbyrussell/oh-my-zsh plugins/themes
        robbyrussell/oh-my-zsh plugins/vundle
        robbyrussell/oh-my-zsh plugins/web-search
        robbyrussell/oh-my-zsh plugins/z

        zlsun/umake
        zlsun/solarized-man

        rimraf/k

        zsh-users/zsh-syntax-highlighting
        zsh-users/zsh-completions src
        zsh-users/zsh-history-substring-search

        # autosuggestions should be loaded last
        tarruda/zsh-autosuggestions

EOBUNDLES

    zgen load zlsun/avit-mod avit-mod

    zgen save
fi

# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# bind UP and DOWN arrow keys (compatibility fallback
# for Ubuntu 12.04, Fedora 21, and MacOSX 10.9 users)
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# bind P and N for EMACS mode
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Enable autosuggestions automatically.
zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init

# ========================= User configuration =========================

# functions

find_duplicate() {
    local dir=${1:-.}
    find $dir -type f -print0                   \
        | xargs -0 -n1 md5sum                   \
        | sort -k 1,32                          \
        | uniq -w 32 -d --all-repeated=separate \
        | sed -e 's/^[0-9a-f]*\ *//;'
}

top_commands() {
    cat ~/.zsh_history                                        \
        | cut -d ';' -f 2- 2>/dev/null                        \
        | awk '{a[$1]++ } END{for(i in a){print a[i] " " i}}' \
        | sort -rn                                            \
        | head $*
}

fawk() {
    eval "awk '{print \$${1}}'"
}

# key bindings

bindkey -s '^Z' '^qfg\n'

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char

bindkey -M menuselect 'a' vi-backward-char
bindkey -M menuselect 's' vi-down-line-or-history
bindkey -M menuselect 'w' vi-up-line-or-history
bindkey -M menuselect 'd' vi-forward-char

bindkey -M menuselect '/' accept-and-infer-next-history
bindkey -M menuselect '.' undo
bindkey -M menuselect ' ' accept-and-hold
bindkey -M menuselect ';' history-incremental-search-forward

# aliases

alias -s html='x-www-browser'
alias -s pdf='xdg-open'

alias -g X='| xargs'
alias -g S='| sort'

autoload -U zmv
alias mmv='noglob zmv -W'

# enable alias when use sudo
# http://askubuntu.com/a/22043/399470
alias sudo='sudo'
alias s='sudo '

alias c='cat'
alias e='echo'
alias m='make'
alias f='eval $(thefuck $(fc -ln -1))'

alias k='k -h'
alias ka='k -h -A'

alias v='vim'
alias svi='sudo vim'
alias vimrc='vim ~/.vimrc'

alias gg='git gui'

alias sga='sudo apt-get autoremove'
alias sgc='sudo apt-get autoclean'
alias sgd='sudo apt-get dist-upgrade'
alias sgg='sudo apt-get upgrade'
alias sgi='sudo apt-get install'
alias sgp='sudo apt-get remove --purge'
alias sgr='sudo apt-get remove'
alias sgu='sudo apt-get update'
alias sgs='apt-cache search'
alias sgf='apt-file search'

alias howdoi='howdoi -c'
alias how='howdoi'
alias howsh='howdoi shell'
alias howpy='howdoi python'
alias howc='howdoi c'
alias howcp='howdoi c++'
alias howjv='howdoi java'
alias howml='howdoi html'
alias howjs='howdoi js'
alias howcss='howdoi css'

alias py='python'
alias py2='python2'
alias py3='python3'
alias pyhttp='python -m SimpleHTTPServer'
alias pyftp='python -m pyftpdlib'

if [[ "$ENABLE_CORRECTION" == "true" ]]; then
    alias touch='nocorrect touch'
    alias xclip='nocorrect xclip'
    alias howdoi='nocorrect howdoi'
    alias _z='nocorrect _z'
fi

eval `dircolors ~/.dircolors`

